'use strict';

const ENUM_ACTIVITY_TYPE_SURVEY = 'SURVEY';
const ENUM_ACTIVITY_TYPE_POLL = 'POLL';
const ENUM_ACTIVITY_TYPE_BOARD = 'BOARD';
const ENUM_ACTIVITY_STATUS_OPEN = 'OPEN';
const ENUM_ACTIVITY_STATUS_CLOSED = 'CLOSED';
const ENUM_ACTIVITY_STATUS_BLOCKED = 'BLOCKED';
const ENUM_ACTIVITY_STATUS_DELETED = 'DELETED';

module.exports = {
    ENUM_ACTIVITY_TYPE_SURVEY,
    ENUM_ACTIVITY_TYPE_POLL,
    ENUM_ACTIVITY_TYPE_BOARD,
    ENUM_ACTIVITY_STATUS_OPEN,
    ENUM_ACTIVITY_STATUS_CLOSED,
    ENUM_ACTIVITY_STATUS_BLOCKED,
    ENUM_ACTIVITY_STATUS_DELETED,
};
