'use strict';

const ENUM_BUDGET_TYPE_SYSTEM = 0;
const ENUM_BUDGET_TYPE_FUND = 1;

const ENUM_BUDGET_STATE_INVALID = 0;
const ENUM_BUDGET_STATE_CREATED = 1;
const ENUM_BUDGET_STATE_REJECTED = 2;
const ENUM_BUDGET_STATE_ACCEPTED = 3;
const ENUM_BUDGET_STATE_FINISHED = 4;

const ENUM_BUDGET_RESULT_NONE = 0;
const ENUM_BUDGET_RESULT_APPROVED = 1;
const ENUM_BUDGET_RESULT_REJECTED = 2;
const ENUM_BUDGET_RESULT_INVALID_QUORUM = 3;
const ENUM_BUDGET_RESULT_ASSESSMENT_FAILED = 4;

module.exports = {
    ENUM_BUDGET_TYPE_SYSTEM,
    ENUM_BUDGET_TYPE_FUND,
    ENUM_BUDGET_STATE_INVALID,
    ENUM_BUDGET_STATE_CREATED,
    ENUM_BUDGET_STATE_REJECTED,
    ENUM_BUDGET_STATE_ACCEPTED,
    ENUM_BUDGET_STATE_FINISHED,
    ENUM_BUDGET_RESULT_NONE,
    ENUM_BUDGET_RESULT_APPROVED,
    ENUM_BUDGET_RESULT_REJECTED,
    ENUM_BUDGET_RESULT_INVALID_QUORUM,
    ENUM_BUDGET_RESULT_ASSESSMENT_FAILED,
};
