'use strict';

const ENUM_FEEDS_TYPE_NEW_PROPOSAL = 'NEW_PROPOSAL';
const ENUM_FEEDS_TYPE_ASSESS_PENDING = 'ASSESS_PENDING';
const ENUM_FEEDS_TYPE_ASSESS_24HR_DEADLINE = 'ASSESS_24HR_DEADLINE';
const ENUM_FEEDS_TYPE_ASSESS_CLOSED = 'ASSESS_CLOSED';
const ENUM_FEEDS_TYPE_VOTING_START = 'VOTING_START';
const ENUM_FEEDS_TYPE_VOTING_PENDING = 'VOTING_PENDING';
const ENUM_FEEDS_TYPE_VOTING_24HR_DEADLINE = 'VOTING_24HR_DEADLINE';
const ENUM_FEEDS_TYPE_VOTING_CLOSED = 'VOTING_CLOSED';
const ENUM_FEEDS_TYPE_NEW_PROPOSAL_NOTICE = 'NEW_PROPOSAL_NOTICE';
const ENUM_FEEDS_TYPE_NEW_OPINION_COMMENT = 'NEW_OPINION_COMMENT';
const ENUM_FEEDS_TYPE_NEW_OPINION_LIKE = 'NEW_OPINION_LIKE';

module.exports = {
    ENUM_FEEDS_TYPE_NEW_PROPOSAL,
    ENUM_FEEDS_TYPE_ASSESS_PENDING,
    ENUM_FEEDS_TYPE_ASSESS_24HR_DEADLINE,
    ENUM_FEEDS_TYPE_ASSESS_CLOSED,
    ENUM_FEEDS_TYPE_VOTING_START,
    ENUM_FEEDS_TYPE_VOTING_PENDING,
    ENUM_FEEDS_TYPE_VOTING_24HR_DEADLINE,
    ENUM_FEEDS_TYPE_VOTING_CLOSED,
    ENUM_FEEDS_TYPE_NEW_PROPOSAL_NOTICE,
    ENUM_FEEDS_TYPE_NEW_OPINION_COMMENT,
    ENUM_FEEDS_TYPE_NEW_OPINION_LIKE,
};
