'use strict';

const ENUM_FOLLOW_TYPE_PROPOSAL_CREATE = 'PROPOSAL_CREATE';
const ENUM_FOLLOW_TYPE_PROPOSAL_JOIN = 'PROPOSAL_JOIN';
const ENUM_FOLLOW_TYPE_POST = 'POST';

module.exports = {
    ENUM_FOLLOW_TYPE_PROPOSAL_CREATE,
    ENUM_FOLLOW_TYPE_PROPOSAL_JOIN,
    ENUM_FOLLOW_TYPE_POST,
};
