'use strict';

const ENUM_INTERACTION_TYPE_LIKE_PROPOSAL = 'LIKE_PROPOSAL';
const ENUM_INTERACTION_TYPE_LIKE_POST = 'LIKE_POST';
const ENUM_INTERACTION_TYPE_REPORT_PROPOSAL = 'REPORT_PROPOSAL';
const ENUM_INTERACTION_TYPE_REPORT_POST = 'REPORT_POST';
const ENUM_INTERACTION_TYPE_READ_ACTIVITY = 'READ_ACTIVITY';
const ENUM_INTERACTION_TYPE_READ_POST = 'READ_POST';

const ENUM_INTERACTION_ACTION_READ = 'interaction.read';
const ENUM_INTERACTION_ACTION_LIKE = 'interaction.like';
const ENUM_INTERACTION_ACTION_REPORT = 'interaction.report';

module.exports = {
    ENUM_INTERACTION_TYPE_LIKE_PROPOSAL,
    ENUM_INTERACTION_TYPE_LIKE_POST,
    ENUM_INTERACTION_TYPE_REPORT_PROPOSAL,
    ENUM_INTERACTION_TYPE_REPORT_POST,
    ENUM_INTERACTION_TYPE_READ_ACTIVITY,
    ENUM_INTERACTION_TYPE_READ_POST,
    ENUM_INTERACTION_ACTION_READ,
    ENUM_INTERACTION_ACTION_LIKE,
    ENUM_INTERACTION_ACTION_REPORT,
};
