'use strict';

const ENUM_INTERACTION_TYPE_LIKE_PROPOSAL = 'LIKE_PROPOSAL';
const ENUM_INTERACTION_TYPE_LIKE_POST = 'LIKE_POST';
const ENUM_INTERACTION_TYPE_REPORT_PROPOSAL = 'REPORT_PROPOSAL';
const ENUM_INTERACTION_TYPE_REPORT_POST = 'REPORT_POST';
const ENUM_INTERACTION_TYPE_READ_ACTIVITY = 'READ_ACTIVITY';
const ENUM_INTERACTION_TYPE_READ_POST = 'READ_POST';

module.exports = {
    ENUM_INTERACTION_TYPE_LIKE_PROPOSAL,
    ENUM_INTERACTION_TYPE_LIKE_POST,
    ENUM_INTERACTION_TYPE_REPORT_PROPOSAL,
    ENUM_INTERACTION_TYPE_REPORT_POST,
    ENUM_INTERACTION_TYPE_READ_ACTIVITY,
    ENUM_INTERACTION_TYPE_READ_POST,
};
