'use strict';

const ENUM_MEMBERROLE_TYPE_ADMINISTRATOR = 'ADMINISTRATOR';
const ENUM_MEMBERROLE_TYPE_EDITOR = 'EDITOR';
const ENUM_MEMBERROLE_TYPE_AUDITOR = 'AUDITOR';
const ENUM_MEMBERROLE_TYPE_USER = 'USER';
const ENUM_MEMBERROLE_TYPE_GUEST = 'GUEST';

const ENUM_MEMBERROLE_SCOPE_SYSTEM = 'SYSTEM';
const ENUM_MEMBERROLE_SCOPE_PROPOSAL = 'PROPOSAL';
const ENUM_MEMBERROLE_SCOPE_ACTIVITY = 'ACTIVITY';

const ENUM_MEMBERROLE_STATUS_PENDING = 'PENDING';
const ENUM_MEMBERROLE_STATUS_NORMAL = 'NORMAL';
const ENUM_MEMBERROLE_STATUS_BLOCK = 'BLOCK';
const ENUM_MEMBERROLE_STATUS_LEAVE = 'LEAVE';

module.exports = {
    ENUM_MEMBERROLE_TYPE_ADMINISTRATOR,
    ENUM_MEMBERROLE_TYPE_EDITOR,
    ENUM_MEMBERROLE_TYPE_AUDITOR,
    ENUM_MEMBERROLE_TYPE_USER,
    ENUM_MEMBERROLE_TYPE_GUEST,
    ENUM_MEMBERROLE_SCOPE_SYSTEM,
    ENUM_MEMBERROLE_SCOPE_PROPOSAL,
    ENUM_MEMBERROLE_SCOPE_ACTIVITY,
    ENUM_MEMBERROLE_STATUS_PENDING,
    ENUM_MEMBERROLE_STATUS_NORMAL,
    ENUM_MEMBERROLE_STATUS_BLOCK,
    ENUM_MEMBERROLE_STATUS_LEAVE,
};
