'use strict';

const ENUM_POST_TYPE_SURVEY_RESPONSE = 'SURVEY_RESPONSE';
const ENUM_POST_TYPE_POLL_RESPONSE = 'POLL_RESPONSE';
const ENUM_POST_TYPE_BOARD_ARTICLE = 'BOARD_ARTICLE';
const ENUM_POST_TYPE_COMMENT_ON_ACTIVITY = 'COMMENT_ON_ACTIVITY';
const ENUM_POST_TYPE_COMMENT_ON_POST = 'COMMENT_ON_POST';
const ENUM_POST_TYPE_REPLY_ON_COMMENT = 'REPLY_ON_COMMENT';

const ENUM_POST_STATUS_OPEN = 'OPEN';
const ENUM_POST_STATUS_DELETED = 'DELETED';

module.exports = {
    ENUM_POST_TYPE_SURVEY_RESPONSE,
    ENUM_POST_TYPE_POLL_RESPONSE,
    ENUM_POST_TYPE_BOARD_ARTICLE,
    ENUM_POST_TYPE_COMMENT_ON_ACTIVITY,
    ENUM_POST_TYPE_COMMENT_ON_POST,
    ENUM_POST_TYPE_REPLY_ON_COMMENT,
    ENUM_POST_STATUS_OPEN,
    ENUM_POST_STATUS_DELETED,
};
