'use strict';

const ENUM_PROPOSAL_TYPE_SYSTEM = 'SYSTEM';
const ENUM_PROPOSAL_TYPE_BUSINESS = 'BUSINESS';

const ENUM_PROPOSALINFO_TYPE_FUND = 'FUND';
const ENUM_PROPOSALINFO_TYPE_SYSTEM = 'SYSTEM';

const ENUM_PROPOSAL_STATUS_CREATED = 'CREATED';
const ENUM_PROPOSAL_STATUS_PENDING_ASSESS = 'PENDING_ASSESS';
const ENUM_PROPOSAL_STATUS_ASSESS = 'ASSESS';
const ENUM_PROPOSAL_STATUS_PENDING_VOTE = 'PENDING_VOTE';
const ENUM_PROPOSAL_STATUS_VOTE = 'VOTE';
const ENUM_PROPOSAL_STATUS_REJECT = 'REJECT';
const ENUM_PROPOSAL_STATUS_CANCEL = 'CANCEL';
const ENUM_PROPOSAL_STATUS_DELETED = 'DELETED';
const ENUM_PROPOSAL_STATUS_CLOSED = 'CLOSED';

const ENUM_FEE_STATUS_WAIT = 'WAIT';
const ENUM_FEE_STATUS_MINING = 'MINING';
const ENUM_FEE_STATUS_PAID = 'PAID';
const ENUM_FEE_STATUS_EXPIRED = 'EXPIRED';
const ENUM_FEE_STATUS_INVALID = 'INVALID';
const ENUM_FEE_STATUS_IRRELEVANT = 'IRRELEVANT';

const ENUM_ASSESS_PROPOSAL_STATE_INVALID = 'INVALID';
const ENUM_ASSESS_PROPOSAL_STATE_CREATED = 'CREATED';
const ENUM_ASSESS_PROPOSAL_STATE_REJECTED = 'REJECTED';
const ENUM_ASSESS_PROPOSAL_STATE_ACCEPTED = 'ACCEPTED';

const ENUM_VOTE_PROPOSAL_STATE_NONE = 'NONE';
const ENUM_VOTE_PROPOSAL_STATE_RUNNING = 'RUNNING';
const ENUM_VOTE_PROPOSAL_STATE_APPROVED = 'APPROVED';
const ENUM_VOTE_PROPOSAL_STATE_WITHDRAWN = 'WITHDRAWN';
const ENUM_VOTE_PROPOSAL_STATE_REJECTED = 'REJECTED';
const ENUM_VOTE_PROPOSAL_STATE_INVALID_QUORUM = 'INVALID_QUORUM';
const ENUM_VOTE_PROPOSAL_STATE_ASSESSMENT_FAILED = 'ASSESSMENT_FAILED';

function needCreateNotification(status) {
    switch (status) {
        case ENUM_PROPOSAL_STATUS_PENDING_ASSESS:
        case ENUM_PROPOSAL_STATUS_ASSESS:
        case ENUM_PROPOSAL_STATUS_PENDING_VOTE:
        case ENUM_PROPOSAL_STATUS_VOTE:
            return true;
        default:
            return false;
    }
}

module.exports = {
    ENUM_PROPOSAL_TYPE_SYSTEM,
    ENUM_PROPOSAL_TYPE_BUSINESS,
    ENUM_PROPOSALINFO_TYPE_FUND,
    ENUM_PROPOSALINFO_TYPE_SYSTEM,
    ENUM_PROPOSAL_STATUS_CREATED,
    ENUM_PROPOSAL_STATUS_PENDING_ASSESS,
    ENUM_PROPOSAL_STATUS_ASSESS,
    ENUM_PROPOSAL_STATUS_PENDING_VOTE,
    ENUM_PROPOSAL_STATUS_VOTE,
    ENUM_PROPOSAL_STATUS_REJECT,
    ENUM_PROPOSAL_STATUS_CANCEL,
    ENUM_PROPOSAL_STATUS_DELETED,
    ENUM_PROPOSAL_STATUS_CLOSED,
    ENUM_FEE_STATUS_WAIT,
    ENUM_FEE_STATUS_MINING,
    ENUM_FEE_STATUS_PAID,
    ENUM_FEE_STATUS_EXPIRED,
    ENUM_FEE_STATUS_INVALID,
    ENUM_FEE_STATUS_IRRELEVANT,
    ENUM_ASSESS_PROPOSAL_STATE_INVALID,
    ENUM_ASSESS_PROPOSAL_STATE_CREATED,
    ENUM_ASSESS_PROPOSAL_STATE_REJECTED,
    ENUM_ASSESS_PROPOSAL_STATE_ACCEPTED,
    ENUM_VOTE_PROPOSAL_STATE_NONE,
    ENUM_VOTE_PROPOSAL_STATE_RUNNING,
    ENUM_VOTE_PROPOSAL_STATE_APPROVED,
    ENUM_VOTE_PROPOSAL_STATE_WITHDRAWN,
    ENUM_VOTE_PROPOSAL_STATE_REJECTED,
    ENUM_VOTE_PROPOSAL_STATE_INVALID_QUORUM,
    ENUM_VOTE_PROPOSAL_STATE_ASSESSMENT_FAILED,
    needCreateNotification,
};
