'use strict';

const ENUM_QUESTION_TYPE_SINGLE_CHOICE = 'SINGLE_CHOICE';
const ENUM_QUESTION_TYPE_SCALE = 'SCALE';

module.exports = {
    ENUM_QUESTION_TYPE_SINGLE_CHOICE,
    ENUM_QUESTION_TYPE_SCALE,
};
